export const investmentplans = [
  {
    name: "Silver Plan",
    //  title: currentStrings.Dashboard.invest.plan_title.a,
    rate: 5,
    min_rate: 5,
    max_rate: 10,
    duration: 24,
    lot: 50,
    max: 5000,
    hrs: 24,
  },
  {
    name: "Gold Plan",
    //  title: currentStrings.Dashboard.invest.plan_title.b,
    rate: 10,
    min_rate: 15,
    max_rate: 25,
    duration: 48,
    lot: 5100,
    max: 10000,
    hrs: 24,
  },
  {
    name: "Diamond plan",
    //  title: currentStrings.Dashboard.invest.plan_title.c,
    rate: 25,
    min_rate: 30,
    max_rate: 40,
    duration: 34,
    lot: 10000,
    max: 25000,
    hrs: 96,
  },

  // mining plans
  {
    name: "Silver Plan",
    //  title: currentStrings.Dashboard.invest.plan_title.a,
    rate: 15,
    min_rate: 5,
    max_rate: 10,
    duration: 24,
    lot: 1000,
    max: 10000,
    hrs: 96,
  },
  {
    name: "Gold Plan",
    //  title: currentStrings.Dashboard.invest.plan_title.b,
    rate: 30,
    min_rate: 15,
    max_rate: 25,
    duration: 24,
    lot: 10000,
    max: 15000,
    hrs: 96,
  },
  {
    name: "Diamond Plan",
    //  title: currentStrings.Dashboard.invest.plan_title.c,
    rate: 50,
    min_rate: 30,
    max_rate: 40,
    duration: 34,
    lot: 15000,
    max: 25000,
    hrs: 96,
  },
];
