export const blocks = [
  {
    name: "Silver Plan",
    //  title: currentStrings.Dashboard.invest.plan_title.a,
    rate: 8,
    min_rate: 5,
    max_rate: 10,
    duration: 14,
    lot: 100,
    max: 4999,
    hrs: 24,
  },
  {
    name: "Gold Plan",
    //  title: currentStrings.Dashboard.invest.plan_title.b,
    rate: 10,
    min_rate: 15,
    max_rate: 25,
    duration: 28,
    lot: 5000,
    max: 9999,
    hrs: 48,
  },
  {
    name: "Diamond plan",
    //  title: currentStrings.Dashboard.invest.plan_title.c,
    rate: 25,
    min_rate: 30,
    max_rate: 40,
    duration: 24,
    lot: 10000,
    max: 0, //  25000,
    hrs: 96,
  },

  // mining plans
  {
    name: "Silver Plan",
    //  title: currentStrings.Dashboard.invest.plan_title.a,
    rate: 15,
    min_rate: 5,
    max_rate: 10,
    duration: 34,
    lot: 1000,
    max: 9999,
    hrs: 48,
  },
  {
    name: "Gold Plan",
    //  title: currentStrings.Dashboard.invest.plan_title.b,
    rate: 30,
    min_rate: 15,
    max_rate: 25,
    duration: 24,
    lot: 10000,
    max: 29000,
    hrs: 96,
  },
  {
    name: "Diamond Plan",
    //  title: currentStrings.Dashboard.invest.plan_title.c,
    rate: 50,
    min_rate: 30,
    max_rate: 40,
    duration: 34,
    lot: 30000,
    max: 0,
    hrs: 96,
  },
];
